django/my_blog/dw_blog/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from my_blog import settings
from . import views
from dw_blog.feeds import AllPostsRssFeed

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # media文件路径配置 重点

django/my_blog/my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('dw_blog.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('users.urls')),
    url(r'^users/', include('users.urls')),
    # 将 auth 应用中的 urls 模块包含进来
    url(r'^users/', include('django.contrib.auth.urls')),
]

django/my_blog/users/urls.py
from django.conf.urls import url, include
from . import views


app_name = 'users'
urlpatterns = [

    url(r'^register/', views.register, name='register'),

]

django/my_blog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}

<html>
<head>
    <title>DW-blog</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <!--<link rel="stylesheet" href="css/bootstrap.min.css">-->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!--<link rel="stylesheet" href="css/pace.css">-->
    <!--<link rel="stylesheet" href="css/custom.css">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">

    <!-- js -->
    <!--<script src="js/jquery-2.1.3.min.js"></script>-->
    <!--<script src="js/bootstrap.min.js"></script>-->
    <!--<script src="js/pace.min.js"></script>-->
    <!--<script src="js/modernizr.custom.js"></script>-->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

    <script>

        $(function () {

//        // 点击之后增加阅读量
//        $('.widget-recent-posts li a').click(function () {
//
//            var url = $(this).attr('href');
//            $.ajax({
//                url: url,
//                type: 'GET',
//                data: {'data': 'click'},
//                dataType: 'json',
//                async: false,
//                success: function () {
//
//                }
//
//            })
//        })

            $('.widget-tag-cloud ul li').mouseover(function () {

                $(this).css({'background-color': '#00BB00'});
                $(this).find('a').css({'color': 'white'})
            });

            $('.widget-tag-cloud ul li').mouseleave(function () {

                $(this).css({'background-color': 'white'});
                $(this).find('a').css({'color': 'black'})
            })
    })
    </script>

    {% block jsp %}
    {% endblock jsp %}
</head>

<body>
<!--&lt;!&ndash; particles.js container &ndash;&gt;-->
<!--<div id="particles-js"></div>-->
<!--&lt;!&ndash; scripts &ndash;&gt;-->
<!--<script src="{% static 'js/particles.js' %}"></script>-->
<!--<script src="{% static 'js/app.js' %}"></script>-->

<!--&lt;!&ndash; stats.js &ndash;&gt;-->
<!--<script src="{% static 'js/lib/stats.js' %}"></script>-->


<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="dw_blog/index.html"><b>DW</b> - Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/">Home</a></li>
                            <li class="cl-effect-11"><a href="full-width.html">Gallery</a></li>
                            <li class="cl-effect-11"><a href="about.html">About</a></li>
                            <li class="cl-effect-11"><a href="contact.html">Contact</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-10">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-2" style="border-left: 1px orangered dashed;">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">NEW POSTS</h3>
                    {% get_recent_posts user.username as recent_post_list %}
                    <ul>
                    {% if user.is_authenticated %}
                        {% for post in recent_post_list %}
                        <li class="post-list">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章
                        {% endfor %}
                    {% endif %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">ARCHIVES</h3>
                    {% archives user.username as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年 {{ date.month }}
                                月</a>
                        </li>
                        {% empty %}
                        暂无文章
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">CATEGORIES</h3>
                    {% get_categories user.username as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                            <span class="post-count">{{ category.num_posts }}</span>
                        </li>
                            {% empty %}
                            暂无分类
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">CLOUD TAGS</h3>
                    {% block tags %}
                    {% get_tags user.username as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                            {% empty %}
                            暂无标签
                        {% endfor %}
                    </ul>

                    {% endblock tags %}
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 -
                    - 来自<a href="http://www.dwbaron.com/" target="_blank">DW</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="dw_blog/index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>